Models/Records.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace VehicleTracker.Models
{
    public class Records
    {
        [Key]
        public int Id { get; set; }

        public int VehicleId { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime? Date { get; set; } = DateTime.Now;

        [Column(TypeName = "nvarchar(10)")]
        [DisplayFormat(DataFormatString = "{0:0,000}", ApplyFormatInEditMode = true)]
        public int? Mileage { get; set; }

        [Column(TypeName = "nvarchar(200)")]
        public string Name { get; set; }
        [Column(TypeName = "nvarchar(500)")]
        public string? Notes { get; set; }

        [DisplayFormat(DataFormatString = "{0:N}", ApplyFormatInEditMode = true)]
        public double? Cost { get; set; }

        public int? CategoryId { get; set; }
        public Category? Caterogy { get; set; }
    }
}

Models/RecordsViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace VehicleTracker.Models
{
    public class RecordsViewModel
    {
        public int Id { get; set; }
        public int VehicleId { get; set; }


        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime? Date { get; set; }
        public int? Mileage { get; set; }

        public string? Name { get; set; }

        public string? Notes { get; set; }

        public double? Cost { get; set; }

        public int? CategoryId { get; set; }

        public List<SelectListItem>? Categories { get; set; }

        public IFormFile? coverImage { get; set; }
    }
}

Controllers/RecordsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Xml.Schema;
using VehicleTracker.Models;

namespace VehicleTracker.Controllers
{
    public class RecordsController : Controller
    {
        private readonly ApplicationDbContext carRep;

        public RecordsController(ApplicationDbContext context)
        {
            carRep = context;
        }

        public async Task<IActionResult> Index(int id, int? category, string? SearchString, string? SortOrder, string? notes)
        {
            ViewBag.carId = id;
            ViewBag.CurrentCategory = category;
            ViewBag.CurrentSearch = SearchString;

            //ViewData["VehicleNotes"] = notes;
            if (notes != null)
            {
                HttpContext.Session.SetString("VehicleNotes", notes);
            }

            //else
            //{
            //    HttpContext.Session.SetString("VehicleNotes", "Nothing here yet..");
            //}


            HttpContext.Session.SetInt32("carid", (int)id);

            if (id == null || carRep.Records == null)
            {
                return NotFound();
            }


            var records = from b in carRep.Records.Where(m => m.VehicleId == id).Where(m => category == null || m.CategoryId == category) select b;

 
            if (!String.IsNullOrEmpty(SearchString))
            {
                records = records.Where(b => b.Name.Contains(SearchString) || b.Notes.Contains(SearchString));
            }

            // Calculate total cost
            double totalCost = (double)records.Sum(m => m.Cost);
            HttpContext.Session.SetString("TotalCost", totalCost.ToString("C2"));


            ViewBag.SortParam = String.IsNullOrEmpty(SortOrder) ? "asc" : "";
            switch (SortOrder)
            {
                case "asc":
                    records = records.OrderBy(b => b.Date);
                    break;
                default:
                    records = records.OrderByDescending(b => b.Date);
                    break;
            }

            //ViewData["VehicleNotes"] = records;

            if (records == null)
            {
                return NotFound();
            }

            return View(records);
        }


        // GET: Records/Create
        [HttpGet]
        public IActionResult Create(int id)
        {
            ViewBag.vehicleId = id;

            //HttpContext.Session.SetInt32("carid", (int)id);
            //ViewBag.Categories = GetCategories();


            var vm = new RecordsViewModel();
            vm.Categories = new List<SelectListItem>
            {
                new SelectListItem {Text="", Value = null},
                new SelectListItem {Text="Maintenance", Value = "1"},
                new SelectListItem {Text="Repair", Value = "2" },
                new SelectListItem {Text="Upgrade", Value = "3" },
                new SelectListItem {Text="Cosmetics", Value = "4" },
                new SelectListItem {Text="Other", Value = "5" }
            };


            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Create(RecordsViewModel addRecord)
        {

            var carid = HttpContext.Session.GetInt32("carid");

            var record = new Records()
            {
                VehicleId = (int)carid,
                Date = addRecord.Date,
                Mileage = addRecord.Mileage,
                Name = addRecord.Name,
                Notes = addRecord.Notes,
                Cost = addRecord.Cost,
                CategoryId = addRecord.CategoryId,
            };

            await carRep.Records.AddAsync(record);
            await carRep.SaveChangesAsync();
            return RedirectToAction("Create");

        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || carRep.Records == null)
            {
                return NotFound();
            }

            var records = await carRep.Records.FindAsync(id);
            if (records == null)
            {
                return NotFound();
            }
            var vm = new RecordsViewModel();
            vm.Categories = new List<SelectListItem>
            {
                new SelectListItem {Text="", Value = null},
                new SelectListItem {Text="Maintenance", Value = "1"},
                new SelectListItem {Text="Repair", Value = "2" },
                new SelectListItem {Text="Upgrade", Value = "3" },
                new SelectListItem {Text="Cosmetics", Value = "4" },
                new SelectListItem {Text="Other", Value = "5" }
            };

            vm.Date = records.Date;
            vm.Mileage = records.Mileage;
            vm.Name = records.Name;
            vm.Notes = records.Notes;
            vm.Cost = records.Cost;



            return View(vm);

            //return View(records);
        }

        // POST: Records/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,VehicleId,Date,Mileage,Name,Notes,Cost,CategoryId")] Records records)
        {
            var CarID = HttpContext.Session.GetInt32("carid");
            records.VehicleId = (int)CarID;
            if (id != records.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    carRep.Update(records);
                    await carRep.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RecordsExists(records.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", new { id = CarID });
            }
            return View(records);
        }

        // GET: Records/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || carRep.Records == null)
            {
                return NotFound();
            }

            var records = await carRep.Records
                .FirstOrDefaultAsync(m => m.Id == id);
            if (records == null)
            {
                return NotFound();
            }

            return View(records);
        }

        // POST: Records/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var CarID = HttpContext.Session.GetInt32("carid");
            if (carRep.Records == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Records'  is null.");
            }
            var records = await carRep.Records.FindAsync(id);
            if (records != null)
            {
                carRep.Records.Remove(records);
            }

            await carRep.SaveChangesAsync();
            return RedirectToAction("Index", new { id = CarID });
        }

        //GET: Records/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || carRep.Records == null)
            {
                return NotFound();
            }

            var records = await carRep.Records
                .FirstOrDefaultAsync(m => m.Id == id);
            if (records == null)
            {
                return NotFound();
            }

            return View(records);
        }

        private bool RecordsExists(int id)
        {
            return (carRep.Records?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        private List<SelectListItem> GetCategories()
        {
            var lstCategories = new List<SelectListItem>();

            List<Category> categories = carRep.Category.ToList();

            lstCategories = categories.Select(ct => new SelectListItem()
            {
                Value = ct.Name,
            }).ToList();

            return lstCategories;
        }
    
    }
}

Controllers/VehicleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VehicleTracker.Models;
using VehicleTracker.Services;

namespace VehicleTracker.Controllers
{
    public class VehicleController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly FileUploadService _fileupload;

        private readonly IWebHostEnvironment _web;

        public VehicleController(ApplicationDbContext context, FileUploadService fileUploadService, IWebHostEnvironment web)
        {
            _context = context;
            _fileupload = fileUploadService;
            _web = web;
        }



        // GET: Vehicles
        public async Task<IActionResult> Index()
        {
            return _context.Vehicles != null ?
                        View(await _context.Vehicles.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Vehicles'  is null.");
        }

        // GET: Vehicles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Vehicles == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        // GET: Vehicles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Vehicles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Make,CarModel,Year")] Vehicle vehicle, IFormFile? file)
        {

            //var filename = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');
            //var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", file.FileName);
            //using (System.IO.Stream stream = new FileStream(path, FileMode.Create))
            //{
            //    await file.CopyToAsync(stream);
            //}

            ///////

            //await _fileupload.UploadFile(file);


            //////

            if (ModelState.IsValid)
            {
                //string imgtxt = Path.GetExtension(file.FileName);
                //if (imgtxt.Equals(".jpg") || imgtxt.Equals(".JPG"))
                //{
                //    await _fileupload.UploadFile(file);
                //    //var path = Path.Combine(_web.WebRootPath, "Images", file.FileName);
                //    //var stream = new FileStream(path, FileMode.Create);
                //    //await file.CopyToAsync(stream);
                //    vehicle.Image = file.FileName;
                //}

                if (file != null)
                {
                    await _fileupload.UploadFile(file);
                    vehicle.Image = file.FileName;
                }


                _context.Add(vehicle);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }


            //__ORIGINAL

            //if (ModelState.IsValid)
            //{

            //    _context.Add(vehicle);
            //    await _context.SaveChangesAsync();
            //    return RedirectToAction(nameof(Index));
            //}

            return View(vehicle);
        }

        // GET: Vehicles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Vehicles == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicles.FindAsync(id);
            if (vehicle == null)
            {
                return NotFound();
            }
            return View(vehicle);
        }

        // POST: Vehicles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Make,CarModel,Year")] Vehicle vehicle, IFormFile? file)
        {
            if (id != vehicle.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (file != null)
                    {
                        await _fileupload.UploadFile(file);
                        vehicle.Image = file.FileName;
                    }

                    _context.Update(vehicle);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehicleExists(vehicle.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vehicle);
        }

        // GET: Vehicles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Vehicles == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        // POST: Vehicles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Vehicles == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Vehicles'  is null.");
            }
            var vehicle = await _context.Vehicles.FindAsync(id);
            if (vehicle != null)
            {
                _context.Vehicles.Remove(vehicle);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VehicleExists(int id)
        {
            return (_context.Vehicles?.Any(e => e.Id == id)).GetValueOrDefault();
        }


        public async Task<IActionResult> EditNotes(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicles.FindAsync(id);
            if (vehicle == null)
            {
                return NotFound();
            }
            return View(vehicle);
        }

        [HttpPost]
        public async Task<IActionResult> EditNotes(int id, string notes)
        {

            //ViewData["VehicleNotes"] = notes;

            var car = _context.Vehicles.FirstOrDefault(m => m.Id == id);
            car.Notes = notes;


            HttpContext.Session.SetString("VehicleNotes", notes);

            _context.Update(car);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Records", new { id = car.Id, notes = notes });
        }
    }
}

Views/Records/Details.cshtml
@model VehicleTracker.Models.Records

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Records</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Mileage)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Mileage)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cost)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cost)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index" asp-route-id="@Model?.VehicleId">Back to List</a>
</div>

Views/Records/Index.cshtml
@model IEnumerable<VehicleTracker.Models.Records>

@{
    ViewData["Title"] = "Index";
    var carid = ViewBag.carId;
    var CarID = Context.Session.GetInt32("carid");
    var notes = Context.Session.GetString("VehicleNotes");
    var cost = Context.Session.GetString("TotalCost");
}
<html>
<body class="ml-8 bg-gradient-to-br from-indigo-200 to-purple-100 via-cyan-100">
<div class="flex flex-col space-y-1 m-1">
    <div class="h-44">
        <div class="flex flex-row ">
            <div class="w-3/12 h-44">
                <div class="flex flex-col">
                    <div class="h-12 mt-2">
                        <a class="text-white bg-gradient-to-br from-green-400 to-blue-600 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-green-200 font-medium rounded-lg text-sm px-4 py-2.5 text-center me-2 mb-2"asp-controller="Vehicle" asp-action="Index">Back to garage</a>
                    </div>
                        <div class="h-18 mb-1">
                            <h1 class="text-center font-extrabold text-4xl p-3 tracking-wide rounded-3xl border-4 border-indigo-800">Service Records</h1>
                        </div>
                    <div class="h-12 ml-36">
                        <form>
                            <button asp-controller="Records" asp-action="Create" asp-route-id="@CarID" class="inline-flex items-center justify-center w-10 h-10 mr-2 text-indigo-100 transition-colors duration-150 bg-indigo-700 rounded-lg focus:shadow-outline hover:bg-indigo-800">
                                <svg class="w-4 h-4 fill-current" viewBox="0 0 20 20"><path d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" clip-rule="evenodd" fill-rule="evenodd"></path></svg>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="w-9/12 h-44">
                <div class="flex flex-col">
                    <div class="h-6">
                        <h1 class="text-center text-lg underline underline-offset-4">Vehicle's Notes</h1>
                    </div>
                        <p class="h-28 w-fit mt-2 mx-20 self-center whitespace-pre">@notes</p>
                    <div class="h-10 self-end mr-12">
                        <a class="text-left" asp-controller="Vehicle" asp-action="EditNotes" asp-route-id="@CarID"><h1 class="underline underline-offset-"> Edit</h1></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="h-12">
        <div class="flex flex-row">
            <div class="w-40 h-12 ml-2 mt-2 mb-1">
                <a class="text-white bg-gradient-to-br from-green-400 to-blue-600 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-green-200 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" asp-controller="Records" asp-action="Index" asp-route-id="@CarID">All Records</a>
            </div>
            <div class="w-96">
                <form asp-controller="Records" asp-action="Index" asp-route-id="@CarID" asp-route-category="@ViewBag.CurrentCategory">
                    <label for="default-search" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
                    <div class="relative">
                        <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                            <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" />
                            </svg>
                        </div>
                        <input type="text" name="SearchString" class="block w-full p-4 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="" required>
                        <button type="submit" value="Search" class="text-white absolute end-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Search</button>
                    </div>
                </form>
            </div>
                <div class="ml-12 self-center">
                    <a class="underline underline-offset-4 mr-1">Total cost:</a> @cost
            </div>
        </div>
    </div>
    <div class="">
        <div class="flex flex-row">
                <div class="w-40 mr-4 mb-56">
                <div class="flex flex-col mt-14">
                    <div>
                        <h1 class="text-center text-base underline underline-offset-4">Sort by category:</h1>
                    </div>
                    <div class="text-center pt-4 mb-4">
                        <a class="text-white bg-gradient-to-r from-green-400 via-green-500 to-green-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm px-4 py-2.5 text-center me-2 mb-2" asp-controller="Records" asp-action="Index" asp-route-id="@CarID" asp-route-category="1">Maintenance</a>
                    </div>
                    <div class="text-center pt-4 mb-4">
                            <a class="text-white bg-gradient-to-r from-red-400 via-red-500 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-9 py-2.5 text-center me-2 mb-2" asp-controller="Records" asp-action="Index" asp-route-id="@CarID" asp-route-category="2"> Repair </a>
                    </div>
                    <div class="text-center pt-4 mb-4">
                            <a class="text-white bg-gradient-to-r from-cyan-400 via-cyan-500 to-cyan-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-cyan-300 font-medium rounded-lg text-sm px-8 py-2.5 text-center me-2 mb-2" asp-controller="Records" asp-action="Index" asp-route-id="@CarID" asp-route-category="3"> Upgrade  </a>
                    </div>
                    <div class="text-center pt-4 mb-4">
                        <a class="text-white bg-gradient-to-r from-teal-400 via-teal-500 to-teal-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-teal-300 font-medium rounded-lg text-sm px-8 py-2.5 text-center me-2 mb-2" asp-controller="Records" asp-action="Index" asp-route-id="@CarID" asp-route-category="4">Cosmetics</a>
                    </div>
                    <div class="text-center pt-4 mb-4">
                        <a class="text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-9 py-2.5 text-center me-2 mb-2" asp-controller="Records" asp-action="Index" asp-route-id="@CarID" asp-route-category="5">Other</a>
                    </div>
                </div>
            </div>
            <div class="mb-56">
                <div class="relative overflow-x-auto shadow-md sm:rounded-lg ml-1 mt-3">
                    <table class="table-auto w-full text-sm text-left rtl:text-right text-blue-100 dark:text-blue-100">
                        <thead class="text-xs text-white uppercase bg-blue-600 dark:text-white">
                            <tr>
                                <th scope="col" class="px-6 py-3">
                                    <a asp-action="Index" asp-route-id="@CarID" asp-route-category="@ViewBag.CurrentCategory" asp-route-SearchString="@ViewBag.CurrentSearch" asp-route-SortOrder="@ViewBag.SortParam">Date</a>
                                </th>
                                <th scope="col" class="px-6 py-3">
                                    Mileage
                                </th>
                                <th scope="col" class="px-6 py-3">
                                    Name
                                </th>
                                <th scope="col" class="px-6 py-3">
                                    Notes
                                </th>
                                <th scope="col" class="px-6 py-3">
                                    Cost
                                </th>
                                <th scope="col" class="px-6 py-3">
                                    Category
                                </th>
                                <th scope="col" class="px-6 py-3">
                                    Action
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model){
                            <tr class="bg-blue-100 border-b border-blue-400">
                                <th scope="row" class="px-6 py-4 font-medium text-gray-800 whitespace-nowrap dark:text-blue-100">
                                    @Html.DisplayFor(modelItem => item.Date)
                                </th>
                                <td class="px-6 py-4 text-gray-800">
                                    @Html.DisplayFor(modelItem => item.Mileage)
                                </td>
                                <td class="px-6 py-4 text-gray-800">
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td class="px-6 py-4 text-gray-800">
                                    @Html.DisplayFor(modelItem => item.Notes)
                                </td>
                                <td class="px-6 py-4 text-gray-800">
                                    @Html.DisplayFor(modelItem => item.Cost)
                                </td>
                                <td class="px-6 py-4 text-gray-800">
                                    @if (item.CategoryId == 1)
                                    {
                                        @:Maintenance
                                    }
                                    @if (item.CategoryId == 2)
                                    {
                                        @:Repair
                                    }
                                    @if (item.CategoryId == 3)
                                    {
                                        @:Upgrade
                                    }
                                    @if (item.CategoryId == 4)
                                    {
                                        @:Cosmetics
                                    }
                                    @if (item.CategoryId == 5)
                                    {
                                        @:Other
                                    }
                                </td>
                                <td class="px-6 py-4">
                                    <a asp-action="Edit" asp-route-id="@item.Id" asp-route-id="@item.VehicleId" class="font-medium text-gray-800 hover:underline">Edit</a>
                                    <a class="text-gray-800"> | </a>
                                    <a asp-action="Delete" asp-route-id="@item.Id" class="font-medium text-gray-800 hover:underline">Delete</a>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>
</body>
</html>